module.exports = {
   ASSET_TOP                       : "$$",
   CONTRACT_CODE                   : "@1",
   GLOBAL_NAME                     : "@2",
   ALIAS_NAME                      : "@3",
   LOCK_TOKEN_KEY                  : "@4",
   LOCK_TOKEN_SUM_KEY              : "@5",
   AUTHORIZE_KEY                   : "@6",
   ACCOUNT_KEYS                    : "@7",
   ACCOUNT_VOTE_KEY                : "@8",
   ACCOUNT_TRANSFER_KEY            : "@9",
   ACCOUNT_DATA_KEY                :"@10",
   ACCOUNT_CONSENSUS_KEY           :"@11",
   PARENT_ACCOUNT_KEY              :"@12",
   SUB_ACCOUNT_KEY                 :"@13",
   CONTRACT_SUB_ACCOUNT_KEY        :"@14",
   CONTRACT_PARENT_ACCOUNT_KEY     :"@15",
   CONTRACT_NATIVE_TOKEN_KEY       :"@16",
   CONTRACT_NATIVE_TOKEN_OWERN_KEY :"@17",
   CONTRACT_VOTE_KEY               : "@18",
   CONTRACT_VOTE_OUT_KEY           : "@19",
   CONTRACT_VOTE_STAT_KEY          : "@20",
   PLEDGE_TOKEN_TGAS_KEY           : "@29",
   USED_TGAS_KEY                   : "@30",
   FROZEN_TGAS_KEY                 : "@31",
   LAST_TX_HOUR_KEY                : "@32",
   PLEDGE_TOKEN_DISK_KEY           : "@33",
   USED_DISK_KEY                   : "@34",
   CONTRACT_REG_KEY                : "#101",
   CONTRACT_TIME_KEY               : "#102",
   CONTRACT_WORKLOAD_KEY           : "#103",
   CONTRACT_SHARD_KEY              : "#104",
   CONTRACT_TICKETS_KEY            : "#105",
   CONTRACT_TOTAL_TICKETS_KEY      : "#106",
   CONTRACT_POLLABLE_KEY           : "#107",
   CONTRACT_ADVANCE_KEY            : "#108",
   CONTRACT_VALIDATE_KEY           : "#109",
   CONTRACT_EDGE_KEY               : "#110",
   CONTRACT_ARCHIVE_KEY            : "#111",
   CONTRACT_VOTER_KEY              : "#112",
   CONTRACT_VOTE_ADVANCE_KEY       : "#113",
   CONTRACT_VOTE_ADVANCE_TICKET_KEY: "#114",
   CONTRACT_STAKE_VOTE_KEY         : "#115",
   CONTRACT_STAKE_KEY              : "#116",
   CONTRACT_VOTE_ACCOUNT_KEY       : "#117",
   CONTRACT_AWARD_KEY              : "#118",
   CONTRACT_AUDITOR_KEY            : "#119",
   CONTRACT_VALIDATOR_KEY          : "#120",
   CONTRACT_REWARD_KEY             : "#121",
   CONTRACT_VOTE_REWARD_KEY        : "#122",
   CONTRACT_WORKLOAD_REWARD_KEY    : "#123",
   CONTRACT_NODE_REWARD_KEY        : "#124",
}